### ISSUE TITLE
Credentials Expose

### ISSUE THREAD

**Issue by prinako** [pedro-rendeiro/thingsboard-tht#1]
### Token de acesso do ThingsBoard
- Expose
### Senha do wifi 
- Expose

Se tudo isso não for credenciais reais, você pode fechar o **Issues**.

**Comment by opedrorendeiro** [comment]
Obrigado pelo alerta, @prinako 

Era apenas uma rede temporária, então creio que não seja problema manter

**Comment by prinako** [comment]
Ah sim que bom assim
